trigger: none

variables:
  WindowsContainerImage: cdpxwin1809.azurecr.io/global/vse2019:latest
  LinuxContainerImage: cdpxlinux.azurecr.io/user/container-plat/golang:1.13.10

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    stages:
    - stage: build_repo
      jobs:

      - job: version
        pool:
          type: linux
        variables:
          ob_outputDirectory: '$(Build.StagingDirectory)'
        steps:
        - script: |
            export QQQ=zzz$(sh ./version.sh)
            echo ##vso[task.setvariable variable=kevparversion]yyy$QQQ
            echo setting ver to $QQQ
        - script: |
            env
        - task: onebranch.pipeline.version@1
          inputs:
            system: 'Custom'
            customVersion: '$(kevparversion)'

      - job: build
        pool:
          type: linux
        variables:
          ob_outputDirectory: '$(Build.StagingDirectory)'
        steps:
        - script: |
            sh ./build.sh
            mkdir $BUILD_STAGINGDIRECTORY/out
            cp --recursive ./cdpx-artifacts/* $BUILD_STAGINGDIRECTORY/out

      - job: sign
        dependsOn: build
        pool:
          type: windows
        variables:
          ob_outputDirectory: '$(Build.StagingDirectory)'
        steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: 'drop_build_repo_build'
            itemPattern: '/out'
            targetPath: '$(Build.StagingDirectory)/out'
        - task: onebranch.pipeline.signing@1
          inputs:
            command: 'sign'
            signing_environment: 'azure-ado'
            files_to_sign: '**/*.exe'
            search_root: '$(Build.StagingDirectory)/out'

      - job: package
        dependsOn: sign
        pool:
          type: linux
        variables:
          ob_outputDirectory: '$(Build.StagingDirectory)'
        steps:
        - task: UniversalPackages@0
          inputs:
            command: 'publish'
            publishDirectory: '$(Build.StagingDirectory)'
            feedsToUsePublish: 'internal'
            vstsFeedPublish: 'ContainerPlatform/ContainerPlat-Dev'
            vstsFeedPackagePublish: 'kevpar-test'
            versionOption: 'patch'