trigger: none

variables:
  WindowsContainerImage: cdpxwin1809.azurecr.io/global/vse2019:latest
  LinuxContainerImage: cdpxlinux.azurecr.io/user/container-plat/golang:1.13.10

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    stages:
    - stage: foo
      jobs:
      - job: bar
        pool:
          type: linux
        variables:
          ob_outputDirectory: '$(Build.StagingDirectory)'
        steps:
        - script: |
            env
        - script: |
            sh ./build.sh
            cp --recursive ./cdpx-artifacts/* $BUILD_STAGINGDIRECTORY
        - task: onebranch.pipeline.signing@1
          inputs:
            command: 'sign'
            signing_profile: 'internal_azure_service'
            signing_environment: 'azure-ado'
            search_root: '$(Build.StagingDirectory)'
            files_to_sign: '**'
        - task: UniversalPackages@0
          inputs:
            command: 'publish'
            publishDirectory: '$(Build.StagingDirectory)'
            feedsToUsePublish: 'internal'
            vstsFeedPublish: 'ContainerPlatform/ContainerPlat-Dev'
            vstsFeedPackagePublish: 'kevpar-test'
            versionOption: 'patch'

