trigger:
  - master

schedules:
  - cron: "0 2 * * 6" # run 7PM PST Fri.
    displayName: Weekly SDL Compliance
    branches:
      include:
        - main
    always: true

variables:
  - template: common-variables.yml@self

  # recommended in wiki:
  # https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/codeql-for-yaml-based-azure-pipelines
  # https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/configuring-codeql#configuring-codeql-in-the-build-pipeline-v1x
  - name: LGTM.UploadSnapshot
    value: true

resources:
  repositories:
    - repository: ob-templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/master
    - repository: cplat
      type: git
      name: ContainerPlatform/ContainerPlatform
      ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@ob-templates
  parameters:
    globalSdl:
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\.config\.gdnsuppress
        suppressionSet: default
    stages:
      - template: .pipelines/templates/build/additional-sdl.yml@cplat
