trigger: none

variables:
  WindowsContainerImage: cdpxwin1809.azurecr.io/global/vse2019:latest
  LinuxContainerImage: cdpxlinux.azurecr.io/user/container-plat/golang:1.13.10

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    stages:
    - stage: foo
      variables:
        ob_outputDirectory: '$(Build.SourceDirectory)/out'
      jobs:
      - job: bar
        pool:
          type: linux
        steps:
        - script: |
            mount
            env