trigger: none

variables:
  WindowsContainerImage: cdpxwin1809.azurecr.io/global/vse2019:latest
  LinuxContainerImage: cdpxlinux.azurecr.io/user/container-plat/golang:1.13.10

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    stages:
    - stage: build_repo
      jobs:

      - job: version
        pool:
          type: linux
        variables:
          ob_outputDirectory: '$(Build.StagingDirectory)'
          runNumber: $[counter($(Build.SourceBranch), 1)]
        steps:
        - script: env
        - script: |
            gitVersion=$(git describe --match 'v[0-9]*' --always --long --tags)
            timeStamp=$(date --utc +%Y%m%d)
            ver=ob-${gitVersion}-$BUILD_SOURCEBRANCH-${timeStamp}-$runNumber
            echo '##vso[task.setvariable variable=versionString]$ver'
        - task: onebranch.pipeline.version@1
          inputs:
            system: 'Custom'
            customVersion: '$(versionString)'

      - job: build
        pool:
          type: linux
        variables:
          ob_outputDirectory: '$(Build.StagingDirectory)'
        steps:
        - script: sh ./build.sh $BUILD_STAGINGDIRECTORY/out

      - job: sign
        dependsOn: build
        pool:
          type: windows
        variables:
          ob_outputDirectory: '$(Build.StagingDirectory)'
        steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: 'drop_build_repo_build'
            patterns: 'out/**'
            targetPath: '$(Build.StagingDirectory)'
        - task: onebranch.pipeline.signing@1
          inputs:
            command: 'sign'
            signing_environment: 'azure-ado'
            files_to_sign: '**/*.exe;**/*.dll;**/*.ps1;**/*.psm1'
            search_root: '$(Build.StagingDirectory)/out'